repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  -   id: trailing-whitespace
  -   id: check-yaml
  -   id: check-added-large-files
  -   id: check-ast
  -   id: check-executables-have-shebangs
  -   id: detect-private-key
  -   id: check-json
  -   id: requirements-txt-fixer

- repo: https://github.com/Yelp/detect-secrets
  rev: v1.5.0
  hooks:
  - id: detect-secrets

- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
  -   id: codespell

- repo: https://github.com/gitleaks/gitleaks
  rev: v8.24.2
  hooks:
    - id: gitleaks